services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: server
    ports:
      - 8000:8000
    environment:
      - PORT=8000
    develop:
      watch:
        - action: rebuild
          path: ./cmd/server

  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: client
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - SERVER_URL=server:8000
    depends_on:
      - server
    develop:
      watch:
        - action: rebuild
          path: ./cmd/client
