services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: server
    ports:
      - 8081:8081
    environment:
      - PORT=8081
    develop:
      watch:
        - action: rebuild
          path: ./cmd/server

  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: client
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - SERVER_URL=http://server:8081
    depends_on:
      - server
    develop:
      watch:
        - action: rebuild
          path: ./cmd/client
